### ISSUE TITLE
The app can't run on the Android 10

### ISSUE THREAD

**Issue by qtlark** [rillig/Loop-Player#1]
I occasionally find your app at goole play and find it fit my need perfectly. But when I install it on my phone, I find it can't run. 
I'd be very appreciate that if you have time to fix it, Plz

**Comment by rillig** [comment]
I'm not sure what you mean by "it can't run", it's almost as general as "it doesn't work".

Please describe your problem in more detail, ideally including error messages and screenshots. See [this guide](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) for more help.

**Comment by qtlark** [comment]
I had re-compiled the code and fixed it, I'm very sorry to bother you.
